DP_TIMESHEET_MIS/Models/ViewModels/Timesheet/ApproveTimesheetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DP_TIMESHEET_MIS.Models;
using DP_TIMESHEET_MIS.Models.ViewModels.Home;


namespace DP_TIMESHEET_MIS.Models.ViewModels.Timesheet
{
    public class ApproveTimesheetViewModel : MainViewModel
    {
        public int HeaderID { get; set; }
        public IEnumerable<TimeSheetDetailModel> TimesheetDetail { get; set; }
    }
}

DP_TIMESHEET_MIS/Models/ViewModels/Timesheet/DeleteTimesheetViewModel.cs
using System.Collections.Generic;
using DP_TIMESHEET_MIS.Models.ViewModels.Home;


namespace DP_TIMESHEET_MIS.Models.ViewModels.Timesheet
{
    public class DeleteTimesheetViewModel : MainViewModel
    {
        public int DetailID { get; set; }
    }
}

DP_TIMESHEET_MIS/Models/ViewModels/Timesheet/EditTimesheetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DP_TIMESHEET_MIS.Models;
using DP_TIMESHEET_MIS.Models.ViewModels.Home;


namespace DP_TIMESHEET_MIS.Models.ViewModels.Timesheet
{
    public class EditTimesheetViewModel : MainViewModel
    {
        public int? DetailId { get; set; }

        [Required]
        [Display(Name = "Period")]
        public int? Period { get; set; }

        [Required]
        [Display(Name = "Position")]
        public int? Position { get; set; }

        [Required]
        [Display(Name = "Project")]
        public int? Project { get; set; }

        [Required]
        public DateTime DateFilled { get; set; }

        [Required]
        public int HoursWorked { get; set; }

        [Required]
        public string Location { get; set; }

        public string TaskDescription { get; set; }

        public List<PositionModel> PositionList { get; set; }

        public List<PeriodModel> PeriodList { get; set; }

        public List<ProjectModel> ProjectList { get; set; }

        public IEnumerable<TimeSheetDetailModel> TimeSheetDetail { get; set; }

    }
}

DP_TIMESHEET_MIS/Models/ViewModels/Timesheet/NewTimesheetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using DP_TIMESHEET_MIS.Models.ViewModels.Home;

namespace DP_TIMESHEET_MIS.Models.ViewModels.Timesheet
{
    public class NewTimesheetViewModel : MainViewModel
    {
        [Required]
        [Display(Name = "Period")]
        public int? Period { get; set; }

        [Required]
        [Display(Name = "Position")]
        public int? Position { get; set; }

        [Required]
        [Display(Name = "Project")]
        public int? Project { get; set; }

        [Required]
        public DateTime DateFilled { get; set; }

        [Required]
        public int HoursWorked { get; set; }

        [Required]
        public string Location { get; set; }

        public string TaskDescription { get; set; }

        public List<PositionModel> PositionList { get; set; }

        public List<PeriodModel> PeriodList { get; set; }

        public List<ProjectModel> ProjectList { get; set; }

    }
}

DP_TIMESHEET_MIS/Models/ViewModels/Timesheet/SearchTimesheetDetailViewModel.cs
using DP_TIMESHEET_MIS.Models.ViewModels.Home;
using System.Collections.Generic;

namespace DP_TIMESHEET_MIS.Models.ViewModels.Timesheet
{
    public class SearchTimesheetDetailViewModel : MainViewModel
    {
        public int? Period { get; set; }

        public IEnumerable<TimeSheetDetailModel> TimeSheetDetail { get; set; }
    }
}

DP_TIMESHEET_MIS/Models/ViewModels/Timesheet/SearchTimesheetViewModel.cs
using DP_TIMESHEET_MIS.Models.ViewModels.Home;
using System.Collections.Generic;

namespace DP_TIMESHEET_MIS.Models.ViewModels.Timesheet
{
    public class SearchTimesheetViewModel : MainViewModel
    {
        public string ConsultantName { get; set; }
        public string TimesheetStatus { get; set; }
        public string Period { get; set; }
        public string SearchName { get; set; }

        public IEnumerable<TimeSheetHeaderModel> TimeSheetHeader { get; set; }

        public List<PeriodModel> PeriodList { get; set; }

    }
}

DP_TIMESHEET_MIS/Models/ViewModels/Timesheet/ViewTimesheetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using DP_TIMESHEET_MIS.Models;
using DP_TIMESHEET_MIS.Models.ViewModels.Home;


namespace DP_TIMESHEET_MIS.Models.ViewModels.Timesheet
{
    public class ViewTimesheetViewModel : MainViewModel
    {
        public int HeaderID { get; set; }

        public IEnumerable<TimeSheetDetailModel> TimesheetDetail { get; set; }
    }
}

DP_TIMESHEET_MIS/Controllers/TimesheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DP_TIMESHEET_MIS.Models;
using DP_TIMESHEET_MIS.Models.ViewModels;
using DP_TIMESHEET_MIS.Models.ViewModels.Timesheet;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace DP_TIMESHEET_MIS.Controllers
{
    public class TimesheetController : Controller
    {
        private Common common;
        private DatabaseContext dbContext;
        private IHttpContextAccessor httpContextAccessor;
        private NewTimesheetViewModel tsViewModel;
        private ViewTimesheetViewModel vtsViewModel;
        private SearchTimesheetViewModel searchTsViewModel;


        public TimesheetController(DatabaseContext context, IHttpContextAccessor httpContext_Accessor)
        {
            dbContext = context;
            httpContextAccessor = httpContext_Accessor;
            common = new Common(dbContext, httpContextAccessor);
            tsViewModel = new NewTimesheetViewModel();
            vtsViewModel = new ViewTimesheetViewModel();
            searchTsViewModel = new SearchTimesheetViewModel();
        }

        [HttpGet]
        public IActionResult NewTimesheet()
        {
            // Get Session Data
            var SessionData = common.GetSessionVariables(httpContextAccessor);
            tsViewModel.PeriodList = common.LoadCombo(2) as List<PeriodModel>;
            tsViewModel.ProjectList = common.LoadCombo(3) as List<ProjectModel>;
            tsViewModel.PositionList = common.LoadCombo(4) as List<PositionModel>;
            tsViewModel.SessionData = SessionData;


            return View(tsViewModel);
        }

        [HttpPost]
        public IActionResult NewTimesheet(NewTimesheetViewModel model)
        {
            if (ModelState.IsValid)
            {

                //Get UserIdentity
                var UserName = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var User = dbContext.Users.Include("Consultant").Where(
                    u => u.UserName.Equals(UserName)
                    ).FirstOrDefault();


                var consultant = User.Consultant.ConsultantId;
                var period = model.Period;
                var project = model.Project;
                var datefilled = model.DateFilled;
                var position = model.Position;
                var hoursworked = model.HoursWorked;
                var location = model.Location;
                var taskdescription = model.TaskDescription;
                var timesheetstatus = "Incomplete";

                // Validate Periods
                var periodModel = dbContext.Period.Find(period);
                DateTime PeriodStart = Convert.ToDateTime(periodModel.PeriodStartDate);
                DateTime PeriodStop = Convert.ToDateTime(periodModel.PeriodStopDate);
                int timesheetDuration = (int)(PeriodStop - PeriodStart).TotalDays;

                // Query # Of Timesheets Filled
                int ts_filled = dbContext.TimeSheetDetail.Where(
                    t => t.Header.Period.PeriodId == period).Count();
                if (timesheetDuration == ts_filled)
                {
                    TempData["TimesheetCompleteMsg"] = "You have already filled your timesheet for that period";
                    return RedirectToAction("SearchTimesheet");
                }
                if ((timesheetDuration - ts_filled) == 1)
                {
                    timesheetstatus = "Pending";
                }

                // Query for existing Timesheet For The Period
                var ts_header = dbContext.TimeSheetHeader.FirstOrDefault(
                    t => t.Consultant.ConsultantId == consultant &&
                    t.Period.PeriodId == period &&
                    t.IsActive == true);

                ConsultantModel co = new ConsultantModel() { ConsultantId = (int)consultant };
                ProjectModel pj = new ProjectModel() { ProjectId = (int)project }; dbContext.Attach(pj);
                PositionModel po = new PositionModel() { PositionId = (int)position }; dbContext.Attach(po);
                PeriodModel pd = new PeriodModel() { PeriodId = (int)period };

                var TimesheetHeader = new TimeSheetHeaderModel
                {
                    Consultant = co,
                    Period = pd,
                    TimesheetStatus = timesheetstatus,
                    ApprovedBy = null,
                    RejectedBy = null,
                    DateRejected = null,
                    IsActive = true
                };
                var TimesheetDetail = new TimeSheetDetailModel
                {
                    DateFilled = datefilled,
                    HoursWorked = hoursworked,
                    Location = location,
                    Position = po,
                    Project = pj,
                    TaskDescription = taskdescription
                };


                if (ts_header != null)
                {
                    TimeSheetHeaderModel th = new TimeSheetHeaderModel() { HeaderId = (int)ts_header.HeaderId };
                    TimesheetDetail.Header = th;
                    dbContext.TimeSheetDetail.Add(TimesheetDetail);
                    dbContext.SaveChanges();

                    TempData["SaveTimesheetMsg"] = "Timesheet Saved Successfully";
                    return RedirectToAction("SearchTimesheet");

                }
                else
                {
                    dbContext.TimeSheetHeader.Add(TimesheetHeader);
                    dbContext.SaveChanges();
                    var Pk = TimesheetHeader.HeaderId;

                    TimeSheetHeaderModel th = new TimeSheetHeaderModel() { HeaderId = (int)Pk };
                    TimesheetDetail.Header = th;
                    dbContext.TimeSheetDetail.Add(TimesheetDetail);
                    dbContext.SaveChanges();

                    TempData["SaveTimesheetMsg"] = "Timesheet Saved Successfully";
                    return RedirectToAction("SearchTimesheet");
                }


            }
            var SessionData = common.GetSessionVariables(httpContextAccessor);
            ModelState.AddModelError("TimesheetError", "Please provide the required details");
            model.PeriodList = common.LoadCombo(2) as List<PeriodModel>;
            model.ProjectList = common.LoadCombo(3) as List<ProjectModel>;
            model.PositionList = common.LoadCombo(4) as List<PositionModel>;
            model.SessionData = SessionData;
            return View(model);
        }

        [HttpGet]
        public IActionResult ViewTimesheet(int? id, ViewTimesheetViewModel model)
        {
            var Timesheet = dbContext.TimeSheetDetail
                .Include(p => p.Project)
                .Where(t => t.Header.HeaderId.Equals(id));

            // Get Session Data
            var SessionData = common.GetSessionVariables(httpContextAccessor);
            model.SessionData = SessionData;
            model.TimesheetDetail = Timesheet;
            model.HeaderID = (int)id;
            return View(model);
        }

        [HttpGet]
        public IActionResult EditTimesheet(int? id, EditTimesheetViewModel model, int? ctrl)
        {
            var SessionData = common.GetSessionVariables(httpContextAccessor);
            model.PeriodList = common.LoadCombo(2) as List<PeriodModel>;
            model.ProjectList = common.LoadCombo(3) as List<ProjectModel>;
            model.PositionList = common.LoadCombo(4) as List<PositionModel>;
            model.SessionData = SessionData;

            // Get Data
            var Timesheets = dbContext.TimeSheetDetail
                // .Include("TimeSheetHeader")
                .Include(t => t.Header)
                .Where(p => p.Id == id);

            foreach (var Timesheet in Timesheets)
            {
                model.DetailId = Timesheet.Id;
                model.DateFilled = Timesheet.DateFilled;
                model.HoursWorked = Timesheet.HoursWorked;
                model.Location = Timesheet.Location;
                model.Period = Timesheet.Header.Period.PeriodId;
                model.Position = Timesheet.Position.PositionId;
                model.Project = Timesheet.Project.ProjectId;
                model.TaskDescription = Timesheet.TaskDescription;
            }
            ModelState.Clear();
            return View(model);
        }

        [HttpPost]
        public IActionResult EditTimesheet(int? id, EditTimesheetViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var TimesheetDetail = dbContext.TimeSheetDetail.Find(id);
                    var position = dbContext.Position.FirstOrDefault(x => x.PositionId == model.Position);
                    var project = dbContext.Projects.FirstOrDefault(x => x.ProjectId == model.Project);
                    var period = dbContext.Period.FirstOrDefault(x => x.PeriodId == model.Period);

                    TimesheetDetail.DateFilled = model.DateFilled;
                    TimesheetDetail.HoursWorked = model.HoursWorked;
                    TimesheetDetail.Location = model.Location;
                    TimesheetDetail.TaskDescription = model.TaskDescription;
                    TimesheetDetail.Position = position;
                    TimesheetDetail.Project = project;
                    TimesheetDetail.Header.Period = period;
                    dbContext.Entry(TimesheetDetail).CurrentValues.SetValues(model);
                    dbContext.SaveChanges();

                    TempData["SaveTimesheetMsg"] = "Timesheet Updated Successfully";
                    return RedirectToAction("SearchTimesheet");
                }
                catch (Exception ex)
                {

DP_TIMESHEET_MIS/Views/Timesheet/ApproveTimesheet.cshtml
@*@model IEnumerable<DP_TIMESHEET_MIS.Models.TimeSheetDetailModel>*@
@model DP_TIMESHEET_MIS.Models.ViewModels.Timesheet.ApproveTimesheetViewModel
@{
    ViewData["Title"] = "Approve Timesheet";
}


<section role="main" class="content-body">
    <header class="page-header">
        <h2>Timesheet</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="index.html">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Timesheet</span></li>
                <li><span>Approve</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Approve Timesheet</h2>
                    <p class="panel-subtitle">
                        Please approve or reject the open timesheet.
                    </p>
                </header>
                <div class="panel-body">
                    <div>
                        <div class="alert alert-info" style="text-align:center">
                            <strong>CONSULTANT NAME</strong>
                            <br />
                            October 2018 - November 2019
                        </div>
                    </div>

                    <div class="table-responsive" style="height: 430px">
                        <table class="table table-striped table-bordered mb-none table-font">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th><b>DATE WORKED</b></th>
                                    <th><b>HOURS WORKED</b></th>
                                    <th><b>PROJECT</b></th>
                                    <th><b>TASK DESCRIPTION</b></th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int i = 1;}
                                @foreach (var item in Model.TimesheetDetail)
                                {
                                    <tr>
                                        <td>
                                            <span>@i.</span>
                                        </td>
                                        <td>
                                            @item.DateFilled
                                        </td>
                                        <td>
                                            @item.HoursWorked
                                        </td>
                                        <td>
                                            @item.Project.ProjectDescription
                                        </td>
                                        <td>
                                            @item.TaskDescription
                                        </td>
                                    </tr>
                                    i++;
                                }
                            </tbody>
                        </table>
                    </div>
                    <hr />
                    <form asp-action="ApproveTimesheet" asp-controller="Timesheet" method="post">

                        <input asp-for="HeaderID" name="HeaderID" type="hidden" class="form-control">
                        <div style="float: left;">
                            <button type="submit" class="mb-xs mt-xs mr-xs btn btn-lg btn-success">Approve &nbsp;<i class="fa fa-check"></i></button>
                        </div>
                        <div style="float: right;">
                            @{
                                int HeaderId = Model.HeaderID;
                                <input asp-for="HeaderID" name="HeaderID" type="hidden" class="form-control">
                                <a class="mb-xs mt-xs mr-xs btn btn-lg btn-danger" asp-action="RejectTimesheet" asp-controller="Timesheet" asp-route-id="@HeaderId">
                                    Reject &nbsp;&nbsp;<i class="fa fa-exclamation-triangle"></i>
                                </a>
                            }

                            
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>

DP_TIMESHEET_MIS/Views/Timesheet/SearchTimesheetDetails.cshtml
@model DP_TIMESHEET_MIS.Models.ViewModels.Timesheet.SearchTimesheetDetailViewModel

@{
    ViewData["Title"] = "View Timesheet Details";
}


<section role="main" class="content-body">
    <header class="page-header">
        <h2>Timesheet</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="index.html">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>View</span></li>
                <li><span>Timesheet Details</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">Edit Timesheet Details</h2>
                <p class="panel-subtitle">
                    Please select the timesheet to edit.
                </p>
            </header>
            <div class="panel-body">
                <div class="table-responsive" style="height: 430px">
                    <table class="table table-bordered table-hover mb-none">
                        <thead>
                            <tr>
                                <th></th>
                                <th><b>DATE</b></th>
                                <th><b>HOURS WORKED</b></th>
                                <th><b>PROJECT</b></th>
                                <th><b>POSITION</b></th>
                                <th><b>LOCATION</b></th>
                                <th><b>ACTIONS</b></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 1;}
                            @foreach (var item in Model.TimeSheetDetail)
                            {
                                <tr>
                                    <td>
                                        <span>@i.</span>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DateFilled)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.HoursWorked)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Project.ProjectName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Position.PositionName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Location)
                                    </td>
                                    <td>
                                        @{
                                            var DetailId = item.Id;
                                            // var HeaderId = item.Header.HeaderId;
                                            <a asp-action="EditTimesheet" asp-controller="Timesheet" asp-route-id="@DetailId" class="btn btn-primary"> Edit &nbsp;<i class="fa fa-edit"></i></a>
                                            
                                            <a class="mb-xs mt-xs mr-xs modal-basic btn btn-danger" href="#modalPrimary">Delete &nbsp;<i class="fa fa-trash-o"></i></a>
                                            <div id="modalPrimary" class="modal-block modal-block-primary mfp-hide">
                                                <section class="panel">
                                                    <header class="panel-heading">
                                                        <h2 class="panel-title">Are you sure?</h2>
                                                    </header>
                                                    <div class="panel-body">
                                                        <div class="modal-wrapper">
                                                            <div class="modal-icon">
                                                                <i class="fa fa-question-circle"></i>
                                                            </div>
                                                            <div class="modal-text">
                                                                <h4>Confirm</h4>
                                                                <p>Are you sure that you want to delete this record?</p>
                                                                <input type="hidden" id="DetailId" name="DetailId" value="@DetailId">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <footer class="panel-footer">
                                                        <div class="row">
                                                            <div class="col-md-12 text-right">
                                                                <button id="ConfirmDelete" class="btn btn-primary modal-confirm">Confirm</button>
                                                                <button id="CancelDelete" class="btn btn-default modal-dismiss">Cancel</button>
                                                            </div>
                                                        </div>
                                                    </footer>
                                                </section>
                                            </div>

                                            //<a asp-action="DeleteTimesheet" asp-controller="Timesheet" asp-route-id="@DetailId" class="btn btn-danger"> Delete &nbsp;<i class="fa fa-trash-o"></i></a>
                                        }
                                    </td>
                                </tr>
                                i++;
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </section>
    </div>
</section>


@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {

        });

        $("#ConfirmDelete").click(function () {
            var DetailId = $('#DetailId').val();
            // var HeaderId = $('#HeaderId').val();
            $.ajax({
                url: window.location.href = '@Url.Action("DeleteTimesheetDetail", "Timesheet")/' + DetailId,
                data: {
                    id: id
                }
            }).done(function () {
            });
        })
    </script>
}

DP_TIMESHEET_MIS/Views/Timesheet/ViewTimesheet.cshtml
@*@model IEnumerable<DP_TIMESHEET_MIS.Models.TimeSheetDetailModel>*@
@model DP_TIMESHEET_MIS.Models.ViewModels.Timesheet.ViewTimesheetViewModel
@{
    ViewData["Title"] = "View Timesheet";
}


<section role="main" class="content-body">
    <header class="page-header">
        <h2>Timesheet</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="index.html">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Timesheet</span></li>
                <li><span>View</span></li>
            </ol>

            <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
        </div>
    </header>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">View Timesheet</h2>
                    <p class="panel-subtitle">
                        Please view the open timesheet.
                    </p>
                </header>
                <div class="panel-body">
                    <div>
                        <div class="alert alert-info" style="text-align:center">
                            <strong>CONSULTANT NAME</strong>
                            <br />
                            October 2018 - November 2019
                        </div>
                    </div>

                    <div class="table-responsive" style="height: 430px">
                        <table class="table table-striped table-bordered mb-none table-font">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th><b>DATE WORKED</b></th>
                                    <th><b>HOURS WORKED</b></th>
                                    <th><b>PROJECT</b></th>
                                    <th><b>TASK DESCRIPTION</b></th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int i = 1;}
                                @foreach (var item in Model.TimesheetDetail)
                                {
                                    <tr>
                                        <td>
                                            <span>@i.</span>
                                        </td>
                                        <td>
                                            @item.DateFilled
                                        </td>
                                        <td>
                                            @item.HoursWorked
                                        </td>
                                        <td>
                                            @item.Project.ProjectDescription
                                        </td>
                                        <td>
                                            @item.TaskDescription
                                        </td>
                                    </tr>
                                    i++;
                                }
                            </tbody>
                        </table>
                    </div>
                    <hr />
                    <div style="float: left;">
                        <a class="mb-xs mt-xs mr-xs btn btn-lg btn-default" asp-action="SearchTimesheet" asp-controller="Timesheet"> Back &nbsp;<i class="fa fa-mail-reply "></i></a>

                    </div>
                    <div style="float: right;">
                        <a class="mb-xs mt-xs mr-xs btn btn-lg btn-default" asp-action="SearchTimesheet" asp-controller="Timesheet"> Print &nbsp;<i class="fa fa-print"></i></a>

                    </div>
                </div>
            </section>
        </div>
    </div>
</section>